### ISSUE TITLE
production ?

### ISSUE THREAD

**Issue by nherment** [Concorda/concorda-server#28]
The readme stipulates that we shouldn't use this plugin in production. What's preventing this ?

Just trying to gauge whether to use this package in out project.

Cc @feugy

**Comment by rjrodger** [comment]
I think that is just a leftover from the initial documentation

**Comment by mirceaalexandru** [comment]
@rjrodger @nherment 
My target this week is to prepare this project to be production ready, including documentation and some other small changes.

**Comment by nherment** [comment]
Super, thanks !
