### ISSUE TITLE
Dockerfile / fuge compatibility

### ISSUE THREAD

**Issue by nherment** [Concorda/concorda-server#34]
When using concorda inside of fuge, fuge does not start it automatically because concorda does not have a Dockerfile.

There are workarounds but it'd be great to add one.

**Comment by mirceaalexandru** [comment]
@nherment as we discussed now I am just doing this.

**Comment by mirceaalexandru** [comment]
@nherment 

Fixed.

Take a look please here:
 - https://github.com/nearform/concorda-fuge for a fuge demo system
 - https://github.com/vidi-insights/vidi-dashboard/pull/143 - for using the concorda-client plugin

```
  seneca
    .use('concorda-client')
```
