### ISSUE TITLE
Transport issues

### ISSUE THREAD

**Issue by feugy** [Concorda/concorda-server#47]
The problem was seen on windows, but also reproduced on a linux.

When using the concorda-client to protect an Hapi server, we have timed-out operation with the concorda-dashboard service.
The setup is:
- one mesh-base service
- one concorda-dashboard monolith OR the couple concorda-dasbboard + concorda-rest
- one service (Hapi) with concorda-client

When starting everything in this order, we got errors when accessing http://localhost:3000/auth/login (on the Hapi service):

```
seneca: Action cmd:login,role:auth failed: [TIMEOUT
```

(full log reported by Hapi)

```
    {"msec":2007.5105209997855,"error":"seneca: Action cmd:login,role:auth failed: [TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined].","data":{"timeout":true,"eraro":true,"orig":{"timeout":true,"eraro":true,"orig":{"timeout":true},"code":"action-timeout","gate-executor":true,"package":"gate-executor","msg":"gate-executor: [TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined]","details":{"id":"8l6u3tdf0a03/8gpsmk9kqwua","gate":false,"ungate":false,"time":{"start":1458113546252,"end":1458113548254},"orig$":{"timeout":true},"message$":"[TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined]"},"callpoint":"at null._onTimeout (D:\\Workspaces\\nearForm\\fast\\dashboard-ui\\node_modules\\gate-executor\\gate-executor.js:112:21)"},"code":"act_execute","gate-executor":true,"package":"seneca","msg":"seneca: Action cmd:login,role:auth failed: [TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined].","details":{"id":"8l6u3tdf0a03/8gpsmk9kqwua","gate":false,"ungate":false,"time":{"start":1458113546252,"end":1458113548254},"orig$":{"timeout":true},"message$":"[TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined]","message":"[TIMEOUT:8l6u3tdf0a03/8gpsmk9kqwua:2000<1458113548254-1458113546252:undefined]","pattern":"cmd:login,role:auth","instance":"Seneca/1.3.0/t83mfhpdl5at/1458113540413/12004/-","plugin":{}},"callpoint":"at null._onTimeout (D:\\Workspaces\\nearForm\\fast\\dashboard-ui\\node_modules\\gate-executor\\gate-executor.js:112:21)","seneca":true,"isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
```

This error can also be reproduced when using [concorda-fuge](https://github.com/Concorda/concorda-fuge/issues/7) setup as split concorda-dashboard/concorda-rest.
I think it's related to seneca-mesh pins, and it might also comes from different seneca-transport/sneeze/seneca versions inside chairo and concorda

Here is concorda-service initialization in the Hapi service:

``` javascript
// Hapi server init
const server = new Server({ debug: { request: ['error'] } })
server.connection({
  host: hostname,
  port: process.env.SERVICE_PORT || 3000,
  routes: {
    files: {relativeTo: buildConfig.publicFolder},
    cors: true
  }
})

// Mandatory Hapi plugins to use concorda-client
server.register([bell, cookie, {register: chairo,  options: {
    timeout: 2000,
    secure: true,
    log: {level: 'INFO'}
  }}], (err) => {
    if (err) throw err

    // Concorda-client init
    const seneca = server.seneca
    seneca.use('concorda-client', {restrict: '/api'})

    seneca.ready(() => {
      // Other content plugins, including api wich defined /api protected routes
      server.register([inert, vision, api], (err) => {
        if (err) throw err

        // and so on ...
```

**Comment by nherment** [comment]
Because we're on a project that has a short deadline, we're happy to use our open source work but I'd like to avoid any running around trying to investigate our open source work. We'll not use concorda in the first part of the project and hopefully we can bring it back in later on.
Damien will focus on building a login and take the route of least resistance which, unless we're mistaken, involves a custom implementation without concorda or seneca-mesh involved.

Before we switch back to using concorda in our project, it'd be great to have some continuous integration that includes the windows environment.
On a different note, it'd be great to 1) abstract seneca-mesh from concorda and 2) allow (and document) the integration of concorda in an existing microservice (ie. not standalone).

**Comment by mirceaalexandru** [comment]
The issue seems to be related with default cookie password being less than 32 characters and in Hapi 13 this is required to be at lest this size.

The short term solution seems to downgrade to Hapi 12, and after I run some tests on Hapi 13, to set the cookie password with requires length.

**Comment by mirceaalexandru** [comment]
seneca-transport can now be used for client-concorda communications.

**Comment by mirceaalexandru** [comment]
A default password matching the minimum length was added, however this should be provided in options for maximum security.

https://github.com/Concorda/concorda-client/blob/master/index.js#L22

**Comment by mirceaalexandru** [comment]
I think we can close this. Mesh is no longer supported at least for now.
