### ISSUE TITLE
build out map of currently used API endpoints

### ISSUE THREAD

**Issue by AdrianRossouw** [Concorda/concorda-server#59]
As part of the v2 path, we will be building a node/js client library that wraps around the existing REST API, but to do that we need to have a better idea of exactly what the API looks like at the moment.

@CodeWriterWriter, could you please : 
1. Get concorda up and running locally using fuge and [concorda-fuge](https://github.com/Concorda/concorda-fuge).
2. Try out all the forms in the interface.
3. Write out a document detailing all the API endpoints, and fields they have.

You may want to use the chrome web inspector to capture the network traffic.

Our next steps will involve writing tests for all of the endpoints you discover here.

**Comment by mirceaalexandru** [comment]
some tests are here:
https://github.com/Concorda/concorda/tree/master/test

but I think we need more.

**Comment by CodeWriterWriter** [comment]
{
  settings-submit:{
    url:http://localhost:3050/api/settings
    type: PUT
    content: {
      authType:{google: "0", github: "0", twitter: "0"},
      concordaPublicRegister:"0",
      emailTemplateFolder:null,
      passwordPolicy:{requireLowercase: "0", requireNumeric: "0", requireUppercase: "0", minLength: 6},
      publicRegister:"1",
      userPolicy:{activateAccount: "0", forceChangePassword: "0"}
    }
  }
  applications-edit:{
    url:http://localhost:3050/api/client/{id number such as:44d706f5-e447-42ec-a008-10e86fb15d96}
    type: GET
  }
  applications-edit-submit:{
    url:http://localhost:3050/api/client
    type: PUT
    content: {
      {name: "HAT", protocol: "", host: "", port: "", appkey: "BACIHD"}
    }
  }
  applications-delete: {
    url: http://localhost:3050/api/client/{id number such as:dae6c6fc-b0b1-43c1-b841-4bd590ec184e}
    type: DELETE
  }
  users-add: {
    url: http://localhost:3050/user/add
    type: GET
  }
  users-add-submit: {
    url: http://localhost:3050/api/user
    type: POST
    content: {
      {name: "sxa", email: "xsa@a", password: "123456aA", repeat: "123456aA"}
    }
  }
  users-send-invite: {
    url: http://localhost:3050/api/invite/user
    type: POST
    content: {
      email:
      message:
    }
  }
  users-edit : {
    url: http://localhost:3050/api/user
    type: PUT
    content: {
      {name: "sxa1", email: "xsa@a", orig_email: "xsa@a"}
    }
  }
  users-delete: {
    url: http://localhost:3050/api/user/{id such as: f2a9e3f4-f78b-4f25-94a3-a20aad8e0a9e}
    type: DELETE
  }
  users-close-session {
    url: http://localhost:3050/api/user/{id such as: 6ad4b43f-433a-439a-bbc5-d9a039c93cfa}/session/close
    type: POST
  }
  profile-edit-submit {
    url: http://localhost:3050/auth/update_user
    type: POST
    content: {
      name:Concorda Administrater
      email:admin@concorda.com
      orig_nick:admin@concorda.com
    }
  }
  logout {
    url: http://localhost:3050/auth/logout
    type: POST
  }
}

**Comment by AdrianRossouw** [comment]
thanks @CodeWriterWriter
