### ISSUE TITLE
Version the API to v1 so we can build a v2 later

### ISSUE THREAD

**Issue by AdrianRossouw** [Concorda/concorda-server#60]
The current API is mostly provided by seneca-auth, as exposed by seneca-web. One of the [tasks we have for v2](https://github.com/Concorda/concorda/issues/58) is to build a proper first-class API in it's place.

To allow us to build the client library first, and then switch over to our new backend api, means we will need to version the current api under /api/v1 first.

**Comment by mirceaalexandru** [comment]
It will change like this:

/api/.... -> /api/v1/admin/....
/auth/.... -> /api/v1/auth/...

**Comment by AdrianRossouw** [comment]
that's perfect @mirceaalexandru

**Comment by mirceaalexandru** [comment]
/api/.... -> /api/v1/admin/.... - administraton API
/auth/.... -> /api/v1/auth/... - authentication API
/something_else/.... -> /api/v1/something_else/... - unrestricted/public API

**Comment by mirceaalexandru** [comment]
@AdrianRossouw here is a list of Hapi endpoints, v1:

Auth:
```
post /api/v1/auth/register
get /api/v1/auth/user
post /api/v1/auth/user
post /api/v1/auth/create_reset
post /api/v1/auth/load_reset
post /api/v1/auth/execute_reset
post /api/v1/auth/confirm
post /api/v1/auth/update_user
post /api/v1/auth/change_password
get /api/v1/auth/logout
post /api/v1/auth/logout
get /api/v1/auth/login
post /api/v1/auth/login
```

User:
```
post /api/v1/user/{user_id}/session/close
get /api/v1/user
get /api/v1/user/{userId}
post /api/v1/user
put /api/v1/user
delete /api/v1/user/{userId}
post /api/v1/invite/user
get /validate/{userId}
```

Groups:
```
post /api/v1/user/{userId}/groups
put /api/v1/user/{userId}/groups
get /api/v1/group
get /api/v1/groups
```

Applications
```
post /api/v1/user/{userId}/clients
put /api/v1/user/{userId}/clients
get /api/v1/client
get /api/v1/client/{clientId}
get /api/v1/clients
post /api/v1/client
put /api/v1/client
delete /api/v1/client/{clientId}
```

Settings:
```
get /api/v1/settings
post /api/v1/settings
put /api/v1/settings
```
