### ISSUE TITLE
Allow only configurable number of user sessions at the time

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-server#92]
Only 1 session per user at a given time (login destroys an existing session).

Is this OK? What if the user login in multiple applications, all those applications using Concorda as user authentication provider?

Should number of user sessions be configurable (1 as default value)?

@AdrianRossouw ?

**Comment by AdrianRossouw** [comment]
I definitely think this needs to be configurable. I'd be furious if logging into facebook on my phone logged me out on the desktop, for instance.

**Comment by mirceaalexandru** [comment]
Implementation is done but cannot do the sorting because the date column is "when" an this is a postgres reserved word so cannot be used for sorting.
